%YAML:1.0
#--------------------------------------------------------------------------------------------
# File Path
#--------------------------------------------------------------------------------------------

dataset_dir: /media/mingrui/MyPassport/SLAMdatabase/KITTI/gray/00
save_path: map/keyframe_trajectory.txt




#--------------------------------------------------------------------------------------------
# Camera Parameters
#--------------------------------------------------------------------------------------------
#camera intrinsics
Camera.left.fx: 718.856
Camera.left.fy: 718.856
Camera.left.cx: 607.1928
Camera.left.cy: 185.2157

Camera.right.fx: 718.856
Camera.right.fy: 718.856
Camera.right.cx: 607.1928
Camera.right.cy: 185.2157

# stereo baseline times fx
Camera.bf: 386.1448





#--------------------------------------------------------------------------------------------
# Feature Parameters
#--------------------------------------------------------------------------------------------

numFeatures.initGood: 200
numFeatures.trackingGood: 100
numFeatures.trackingBad: 10

# ORB Extractor: Number of features per image
ORBextractor.nInitFeatures: 400
ORBextractor.nNewFeatures: 200
# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2
# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8
# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7



#--------------------------------------------------------------------------------------------
# Loop Closing Parameters
#--------------------------------------------------------------------------------------------

LCD.similarityScoreThreshold.high: 0.91
LCD.similarityScoreThreshold.low: 0.90




#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 1
Viewer.PointSize:2
Viewer.CameraSize: 0.15
Viewer.CameraLineWidth: 2
Viewer.ViewpointX: 0
Viewer.ViewpointY: -500
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000
